# Preprocessing 

Experimenting with different encoding methods. 

In [2]:
import sys
sys.path.append('../')
import glob2 as glob
import json
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

pd.options.display.max_columns = 200
pd.options.display.max_rows = 200
%matplotlib inline

import warnings; warnings.simplefilter('ignore')

In [5]:
data = pd.read_csv(('data/DPC_pre_split.csv'), index_col='match_id')

In [7]:
y = data[['radiant_win', 'duration']]
X = data.drop(columns=['radiant_win', 'duration'])

In [20]:
heroes_df = X[[f'{i}hero_id' for i in range(1, 23)]]

In [12]:
heroes_df_train = X[[f'{i}hero_id' for i in range(1, 23)]]

In [10]:
heroes_df

1hero_id  2hero_id  3hero_id  4hero_id  5hero_id  6hero_id  \
match_id                                                                 
4833593109        38       111        55       107        46        66   
4833371463       111        38        37        55        88        66   
4833120790        37        38       111        55        88        66   
4835973421        66        52       120        88        55        37   
4835092211        38        65        66       111        88        46   
...              ...       ...       ...       ...       ...       ...   
5114927085        85         7        90        72         9        97   
5114498359        59        66        34         7        57        76   
5056346258        97        72        84        66        79        60   
5060704777       102        86       100        25        97        41   
5055077558        19        60         3        72        79        84   

            7hero_id  8hero_id  9hero_id  10hero_id  11hero_id  12hero_id  \
match_id                                                                    
4833593109        18        16        37         65         57         88   
4833371463        16       102        10         46         65         68   
4833120790        16        18       121         46         65        114   
4835973421        16       102        86         53         18         89   
4835092211        37        68        16         52         86          7   
...              ...       ...       ...        ...        ...        ...   
5114927085        66        81        25        107          5         98   
5114498359        97        90         8         44         47         99   
5056346258        23        85        25          9         86         16   
5060704777        66        90        57         23        114        101   
5055077558        90        23        25        102         93          7   

            13hero_id  14hero_id  15hero_id  16hero_id  17hero_id  18hero_id  \
match_id                                                                       
4833593109         39        121         67         68          7         80   
4833371463        107         18        119          5         23          7   
4833120790         57         95        107         86         17         42   
4835973421        106         47         99         68         77         42   
4835092211        106         82         42         55         71         81   
...               ...        ...        ...        ...        ...        ...   
5114927085         23         65        121         64         96         11   
5114498359         98         33         25         53         29         23   
5056346258         76         54         96         31        106          8   
5060704777         46         10        111         79         72         76   
5055077558         82         10        121         81         18         46   

            19hero_id  20hero_id  21hero_id  22hero_id  
match_id                                                
4833593109         51         43        100        106  
4833371463          8        129         67          2  
4833120790         90         29         68        129  
4835973421         17        113         76         65  
4835092211        107         17        121         76  
...               ...        ...        ...        ...  
5114927085         54         39         41         43  
5114498359         46         93         40         72  
5056346258         57         98        104         41  
5060704777         38         17          4         61  
5055077558         95         47         99         76  

[1162 rows x 22 columns]

## Sklearn OneHotEncoder

In [18]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
X_ohe = enc.fit_transform(X).toarray()
#OneHotEncoder(handle_unknown='ignore')

In [19]:
X_ohe.shape

(1162, 2110)

In [24]:
enc = OneHotEncoder(handle_unknown='ignore')
heroes_df_ohe = pd.DataFrame(enc.fit_transform(heroes_df).toarray())
#OneHotEncoder(handle_unknown='ignore')

In [25]:
heroes_df_ohe.shape

(1162, 2044)

In [27]:
X = X.join(heroes_df_ohe)
X.head()

ValueError: columns overlap but no suffix specified: Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043],
      dtype='object', length=2044)

In [15]:
enc.categories_

[array([1], dtype=int64),
 array([0, 1], dtype=int64),
 array([  2,   3,   4,   6,   7,   9,  10,  16,  18,  19,  23,  25,  27,
         29,  31,  33,  37,  38,  40,  41,  42,  43,  46,  52,  53,  55,
         57,  58,  59,  60,  61,  62,  65,  66,  68,  69,  71,  72,  73,
         74,  75,  76,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  93,  96,  97,  98,  99, 102, 103, 104, 105, 106,
        107, 111, 112, 119, 120, 121, 129], dtype=int64),
 array([1], dtype=int64),
 array([0, 1], dtype=int64),
 array([  2,   3,   4,   7,   9,  10,  16,  17,  18,  19,  22,  23,  25,
         29,  31,  33,  37,  38,  41,  42,  43,  46,  50,  52,  53,  54,
         55,  57,  58,  59,  60,  61,  65,  66,  67,  68,  71,  72,  73,
         74,  76,  78,  79,  80,  81,  83,  84,  85,  86,  88,  89,  90,
         91,  94,  96,  97,  98,  99, 102, 103, 105, 106, 107, 111, 112,
        119, 120, 121, 129], dtype=int64),
 array([1], dtype=int64),
 array([0, 1], dtype=int64),
 arr

In [16]:
enc.transform(X)

<1162x2110 sparse matrix of type '<class 'numpy.float64'>'
	with 76692 stored elements in Compressed Sparse Row format>

In [17]:
enc.transform(X)

<1162x2110 sparse matrix of type '<class 'numpy.float64'>'
	with 76692 stored elements in Compressed Sparse Row format>

## Hero Name Replacement

For my own understanding, I want to take a look at the data with the hero names and the Boolean values before going along with the data as integers.

In [17]:
# # # Getting Heroes ID according to the name
input_file = open('data/heroes.json') 
heroes = json.load(input_file)
input_file.close()

In [19]:
heroes_dict = {}
for i in range (len(heroes['heroes'])):
    hero_id = heroes['heroes'][i]['id']
    hero_name = heroes['heroes'][i]['localized_name']
    heroes_dict[hero_id]= hero_name
def change_hero_name(row):
    if row in heroes_dict:
        return heroes_dict[row]

TypeError: list indices must be integers or slices, not str

In [ ]:
heroes_list = []
for i, j in enumerate(heroes_dict):
    hero_name = heroes_dict[j]
    heroes_list.append(hero_name)